### ISSUE TITLE
QRコードを発行したい

### ISSUE THREAD

**Issue by shamrock1976** [ShamrockRecords/udchat-app#7]
チャットの画面で招待をしやすいようにQRコードやURLをコピーしたりする画面を出したい。チャットから抜けると参加退出ログがつくのでそれを出さないように画面にレイヤーっぽく出したい。

**Comment by MaySoMusician** [comment]
生成自体はこれが使えそう https://github.com/soldair/node-qrcode

**Comment by shamrock1976** [comment]
お、それも試してみるね！

API一発で行けるのでこれでもいいかなって思ってる。クライアント側から呼べばいいし（サーバー負荷軽減w）

https://qiita.com/KOJI-YAMAMOTO/items/103c21d1c471cc2e0a2a

**Comment by shamrock1976** [comment]
二次元バーコードを表示するボタンを追加。
